<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BrandonFintech.Accounts\BrandonFintech.Accounts.csproj" />
    <ProjectReference Include="..\BrandonFintech.Audit\BrandonFintech.Audit.csproj" />
    <ProjectReference Include="..\BrandonFintech.Identity\BrandonFintech.Identity.csproj" />
    <ProjectReference Include="..\BrandonFintech.Payments\BrandonFintech.Payments.csproj" />
    <ProjectReference Include="..\BrandonFintech.Transfers\BrandonFintech.Transfers.csproj" />
  </ItemGroup>

</Project>
